import Foundation

/// Excel dosyasından (Soulmate Coffee - Kötekli Şubesi, 2026 Ocak) birebir
/// aktarılan başlangıç kataloğu. Yeni bir dönem oluşturulduğunda bu liste
/// kullanılır. Bu dosya `scripts` ile xlsx'ten üretilmiştir.
enum SeedData {

    static let branchName = "SOULMATE COFFEE - KÖTEKLİ ŞUBESİ"

    /// STOK TAKİBİ ürün kataloğu (59 ürün).
    static let stockCatalog: [StockItem] = [
        StockItem(name: "Espresso Çekirdek (kg)", group: .sicakIcecek, unit: "KG", unitPrice: 520),
        StockItem(name: "Filtre Kahve (kg)", group: .sicakIcecek, unit: "KG", unitPrice: 450),
        StockItem(name: "Türk Kahvesi (kg)", group: .sicakIcecek, unit: "KG", unitPrice: 380),
        StockItem(name: "Süt (1L)", group: .sicakIcecek, unit: "ADET", unitPrice: 42),
        StockItem(name: "Bitkisel Süt - Yulaf (1L)", group: .sicakIcecek, unit: "ADET", unitPrice: 85),
        StockItem(name: "Bitkisel Süt - Badem (1L)", group: .sicakIcecek, unit: "ADET", unitPrice: 90),
        StockItem(name: "Sıcak Çikolata (kg)", group: .sicakIcecek, unit: "KG", unitPrice: 280),
        StockItem(name: "Matcha Tozu (250g)", group: .sicakIcecek, unit: "ADET", unitPrice: 320),
        StockItem(name: "Chai Latte Tozu (kg)", group: .sicakIcecek, unit: "KG", unitPrice: 250),
        StockItem(name: "Bitki Çayı (kutu)", group: .sicakIcecek, unit: "ADET", unitPrice: 45),
        StockItem(name: "Siyah Çay (kg)", group: .sicakIcecek, unit: "KG", unitPrice: 180),
        StockItem(name: "Vanilya Şurup", group: .sicakIcecek, unit: "ADET", unitPrice: 120),
        StockItem(name: "Karamel Şurup", group: .sicakIcecek, unit: "ADET", unitPrice: 120),
        StockItem(name: "Fındık Şurup", group: .sicakIcecek, unit: "ADET", unitPrice: 120),
        StockItem(name: "Çikolata Sos", group: .sicakIcecek, unit: "ADET", unitPrice: 95),
        StockItem(name: "Whipped Cream (tüp)", group: .sicakIcecek, unit: "ADET", unitPrice: 65),
        StockItem(name: "Damla Su 330ml (24lü)", group: .sogukIcecek, unit: "KOLİ", unitPrice: 95),
        StockItem(name: "Damla Su 500ml (24lü)", group: .sogukIcecek, unit: "KOLİ", unitPrice: 115),
        StockItem(name: "Soda (24lü)", group: .sogukIcecek, unit: "KOLİ", unitPrice: 130),
        StockItem(name: "Coca Cola (24lü)", group: .sogukIcecek, unit: "KOLİ", unitPrice: 310),
        StockItem(name: "Coca Cola Zero (24lü)", group: .sogukIcecek, unit: "KOLİ", unitPrice: 310),
        StockItem(name: "Fuse Tea Şeftali (12li)", group: .sogukIcecek, unit: "KOLİ", unitPrice: 175),
        StockItem(name: "Fuse Tea Limon (12li)", group: .sogukIcecek, unit: "KOLİ", unitPrice: 175),
        StockItem(name: "Cappy Meyve Suyu (12li)", group: .sogukIcecek, unit: "KOLİ", unitPrice: 195),
        StockItem(name: "Schweppes Limon (24lü)", group: .sogukIcecek, unit: "KOLİ", unitPrice: 285),
        StockItem(name: "Schweppes Mandalina (24lü)", group: .sogukIcecek, unit: "KOLİ", unitPrice: 285),
        StockItem(name: "Red Bull (24lü)", group: .sogukIcecek, unit: "KOLİ", unitPrice: 720),
        StockItem(name: "Limonata Konsantre", group: .sogukIcecek, unit: "ADET", unitPrice: 85),
        StockItem(name: "Buzlu Kahve Bazı (lt)", group: .sogukIcecek, unit: "ADET", unitPrice: 140),
        StockItem(name: "Cheesecake (dilim)", group: .gida, unit: "ADET", unitPrice: 45),
        StockItem(name: "Brownie", group: .gida, unit: "ADET", unitPrice: 30),
        StockItem(name: "Cookie", group: .gida, unit: "ADET", unitPrice: 22),
        StockItem(name: "Muffin", group: .gida, unit: "ADET", unitPrice: 25),
        StockItem(name: "Croissant", group: .gida, unit: "ADET", unitPrice: 28),
        StockItem(name: "Sandviç Ekmeği", group: .gida, unit: "ADET", unitPrice: 15),
        StockItem(name: "Tost Ekmeği", group: .gida, unit: "ADET", unitPrice: 12),
        StockItem(name: "Kaşar Peyniri (kg)", group: .gida, unit: "KG", unitPrice: 320),
        StockItem(name: "Sucuk (kg)", group: .gida, unit: "KG", unitPrice: 280),
        StockItem(name: "Domates (kg)", group: .gida, unit: "KG", unitPrice: 45),
        StockItem(name: "Salatalık (kg)", group: .gida, unit: "KG", unitPrice: 35),
        StockItem(name: "Granola (kg)", group: .gida, unit: "KG", unitPrice: 180),
        StockItem(name: "Bal Kavanoz", group: .gida, unit: "ADET", unitPrice: 95),
        StockItem(name: "Karton Bardak S (100lü)", group: .sarf, unit: "ADET", unitPrice: 75),
        StockItem(name: "Karton Bardak M (100lü)", group: .sarf, unit: "ADET", unitPrice: 85),
        StockItem(name: "Karton Bardak L (100lü)", group: .sarf, unit: "ADET", unitPrice: 95),
        StockItem(name: "Plastik Kapak (100lü)", group: .sarf, unit: "ADET", unitPrice: 45),
        StockItem(name: "Pipet (paket)", group: .sarf, unit: "ADET", unitPrice: 25),
        StockItem(name: "Peçete (paket)", group: .sarf, unit: "ADET", unitPrice: 18),
        StockItem(name: "Paket Servis Poşeti (100lü)", group: .sarf, unit: "ADET", unitPrice: 55),
        StockItem(name: "Sleeve / Bardak Kılıfı (100lü)", group: .sarf, unit: "ADET", unitPrice: 40),
        StockItem(name: "Karıştırıcı (paket)", group: .sarf, unit: "ADET", unitPrice: 20),
        StockItem(name: "Şeker Paketi (kg)", group: .sarf, unit: "KG", unitPrice: 42),
        StockItem(name: "Bulaşık Deterjanı", group: .temizlik, unit: "ADET", unitPrice: 120),
        StockItem(name: "Yüzey Temizleyici", group: .temizlik, unit: "ADET", unitPrice: 65),
        StockItem(name: "Cam Temizleyici", group: .temizlik, unit: "ADET", unitPrice: 45),
        StockItem(name: "Dezenfektan", group: .temizlik, unit: "ADET", unitPrice: 85),
        StockItem(name: "Elde Yıkama Sıvısı", group: .temizlik, unit: "ADET", unitPrice: 55),
        StockItem(name: "Çöp Poşeti (rulo)", group: .temizlik, unit: "ADET", unitPrice: 35),
        StockItem(name: "Kağıt Havlu (rulo)", group: .temizlik, unit: "ADET", unitPrice: 45),
    ]

    /// ZAYİ / İKRAM günlük takip ürün listesi (menü kalemleri).
    static let dailyCatalog: [String] = [
        "ESPRESSO S",
        "S.FILTER COFFEE",
        "S.AMERICANO",
        "S.CAFE LATTE",
        "S.CAPPUCCINO",
        "S.CAFE MOCHA",
        "S.W.CHOC.MOCHA",
        "S.CARAMEL LATTE",
        "S.CRM.MACC.",
        "S.FLAT WHITE",
        "S.B.BERRY WHITE CHOC.",
        "S.CINNAMON ROLL LATTE",
        "S.SPICE MANGO LATTE",
        "S.MACADAMIA NUT LATTE",
        "S.MAPLE SPICE LATTE",
        "S.SPANISHA LATTE",
        "ESPRESSO M",
        "M.FILTER COFFEE",
        "M.AMERICANO",
        "M.CAFE LATTE",
        "M.CAPPUCCINO",
        "M.CAFE MOCHA",
        "M.WHT.CHOC.MOCHA",
        "M.CARAMEL LATTE",
        "M.CARAMEL MACCHIATO",
        "M.FLAT WHITE",
        "M.B.BERRY WHITE CHOC.",
        "M.CINNAMON ROLL LATTE",
        "M.SPICE MANGO LATTE",
        "M.MACADAMIA NUT LATTE",
        "M.MAPLE SPICE LATTE",
        "M.SPANISH LATTE",
        "ESPRESSO L",
        "L.FILTER COFFEE",
        "L.AMERICANO",
        "L.CAFE LATTE",
        "L.CAPPUCCINO",
        "L.CAFE MOCHA",
        "L.WHT.CHOC.MOCHA",
        "L.CARAMEL LATTE",
        "L.CARAMEL MACCHIATO",
        "L.FLAT WHITE",
        "L.B.BERRY WHITE CHOC.",
        "L.CINNAMON ROLL LATTE",
        "L.SPICE MANGO LATTE",
        "L.MACADAMIA NUT LATTE",
        "L.MAPLE SPICE LATTE",
        "L.SPANISH LATTE",
        "ICED COFFEE",
        "ICED FILTER COFFEE",
        "ICED AMERICANO",
        "ICED LATTE",
        "ICED MOCHA",
        "ICED WHITE MOCHA",
        "ICED CARAMEL",
        "ICED CHAI TEA LATTE",
        "ICED CRML.MACH.",
        "ICED B.BERRY W. CHOC.",
        "ICED SPICE MANGO LATTE",
        "ICED CINNAMON ROLL LATTE",
        "ICED MACADAMIA NUT LATTE",
        "ICED SPANISH LATTE",
        "FRAPPE",
        "CARAMEL FRAPPE",
        "HAZELNUT FRAPPE",
        "COCO. FRAPPE",
        "CHOC.MOCHA FRAPPE",
        "W.CHOC.MOCHA FRAPPE",
        "ICEPUCCINO",
        "CARAMEL MACADAMIA NUT FRAPPE",
        "WHITE MOCHA BLUEBERRY FRAPPE",
        "MOCHA TANGERİNE FRAPPE",
        "SMOOTHIES",
        "STRAWBERRY SMOOT.",
        "MANGO SMOOT.",
        "MIXY SMOOT.",
        "PASSION FRUIT SMOOT.",
        "JABUTICABA SMOOT.",
        "BUZLU İÇECEK",
        "MILKSHAKE",
        "DONDURMA",
        "BUBBLE TEA",
        "BUB.TEA MANGO",
        "BUB.TEA TROPICAL",
        "LİMONATA & PORT.",
        "LİMONATA",
        "SIK.PORTAKAL",
        "ÇÖRÇİL",
        "ICED TEA",
        "ICED TROPIC TEA",
        "ICED HIBISCUS TEA",
        "ICED YUZU PASSION TEA",
        "ICED CRANBERRY HIBISCUS TEA",
        "ICED PINA COLADO",
        "ICED SPICE MANGO & GREEN TEA",
        "3.NESİL",
        "COLD BREW",
        "COLD BREW  ŞİŞE",
        "HARIO V 60",
        "COLD BREW LATTE",
        "TÜRK KAHVESİ",
        "TÜRK KAHV.TEK.",
        "DOUBLE TÜRK KAHV.",
        "PERS.TÜRK KAH.",
        "ÇAY",
        "ÇAY S - FİNCAN",
        "ÇAY M",
        "ÇAY L",
        "EARL GREY",
        "TROPİKAL YEŞİL ÇAY",
        "KIŞ ÇAYI",
        "R.BERRY BLACK TEA",
        "PERS. ÇAY S.",
        "SICAKLAR S",
        "S.MILK",
        "S.HOT CHOCOLATE",
        "S.HOT WHITE CHOCOLATE",
        "S.SALEP",
        "S.CHAI TEA LATTE",
        "S.SICAK ÇİKOLATA TANGERİNE",
        "SICAKLAR M",
        "M.MILK",
        "M.HOT CHOCOLATE",
        "M.HOT WHITE CHOCOLATE",
        "M.SALEP",
        "M.CHAI TEA LATTE",
        "M.SICAK ÇİKOLATA TANGERİNE",
        "SICAKLAR L",
        "L.MILK",
        "L.HOT CHOC.",
        "L.HOT W.CHOC.",
        "L.SALEP",
        "L.CHAI TEA LATTE",
        "L.SICAK ÇİKOLATA TANGERİNE",
        "PASTA",
        "PASTA TIRAMISU",
        "PASTA FRMB.BELLA",
        "PASTA HAVUÇLU K.",
        "PASTA MARLENKA",
        "PASTA CRUNCHY YAB.MERS.",
        "PASTA COCO STAR",
        "PASTA ORMAN MEYVELİ CUP",
        "PASTA MOZAİK",
        "PASTA LEMON LUSH",
        "PASTA GOLDEN VELVET",
        "PASTA BERRY VELVET",
        "PASTA NUTELLA",
        "CHESEECAKE",
        "CHESEECAKE LİMON",
        "CHESEECAKE FRAMBUAZ",
        "KEK & TURTA",
        "KEK MOZAİK",
        "MUFFİN ÇİFTE ÇİK.",
        "MUFFİN VİŞNELİ",
        "BOMBA",
        "BLUEBERRY & LIME COOKIE",
        "BAKERY",
        "LAUGHING COW ÇÖREK",
        "GURME TEREYAĞLI KRUVASAN",
        "PAIN SUISSE ISPANAKLI PEYNİRLİ  ( 135 Gr.)",
        "AÇMA-PATATES PEYNİR ÖRGÜ",
        "POĞAÇA-DEREOTLU PEYNİRLİ",
        "SANDVIÇ",
        "SAND.BAGEL PEYNİR",
        "SANDVİÇ HİNDİ JAMBON PEYNİRLİ",
        "SANDVİÇ DANA JAM.- MOZARELLA",
        "SANDVİÇ TERİYAKİ TAVUK AVOKADO",
        "SANDVİÇ CİABATTA BEYAZ PEYNİRLİ",
        "KASA ÖNÜ ÜRÜN",
        "BAL KATLA BALLA",
        "CARAMEL WAFFLE",
        "SNACK MİLK CHOCOLATE",
        "BADEM KROKANLI BAR",
        "FELLAS HIGH PROTEIN BAR STRAWBERRY",
        "FELLAS HIGH PROTEIN BAR COCONUT & COCOA",
        "FELLAS DÖRT TOHUMLU KURUYEMİŞ BAR (30 GR. )",
        "LOTUS BİSCOFF BİSKÜVİ",
        "SNACK NUGOTTİ  40 GR",
        "BADEMLİ MİNİ KEK",
        "HAŞHAŞLI KURABİYE",
        "CORNY KAKAO KIRMIZI TAHIL BAR",
        "CORNY KARIŞIK TAHIL BAR",
    ]

    /// Belirli bir dönem için boş (giriş bekleyen) AppData üretir.
    static func makePeriod(year: Int, month: Int) -> AppData {
        AppData(
            branchName: branchName,
            year: year,
            month: month,
            ciro: 0,
            calisanGunSayisi: 0,
            personelMaliyet: 0,
            kira: 0,
            elektrik: 0,
            su: 0,
            dogalgaz: 0,
            internet: 0,
            digerGiderler: 0,
            stock: stockCatalog,
            zayi: dailyCatalog.map { DailyTrackItem(name: $0) },
            ikram: dailyCatalog.map { DailyTrackItem(name: $0) }
        )
    }
}
